<a href="https://colab.research.google.com/github/LX1N/Android-Renk-Ogretici-Oyun/blob/master/ListeBirlestirme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
ekonomi = np.array([1,2,3,4])
deu = np.array([4,5,6,7])

In [2]:
np.concatenate([ekonomi,deu])

array([1, 2, 3, 4, 4, 5, 6, 7])

In [3]:
a = np.array([[1,2,4],
              [1,2,6]])

b = np.array([[2,35,36],
              [53,65,98]])

In [4]:
np.concatenate([a,b],axis=0)

array([[ 1,  2,  4],
       [ 1,  2,  6],
       [ 2, 35, 36],
       [53, 65, 98]])

In [5]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  4,  2, 35, 36],
       [ 1,  2,  6, 53, 65, 98]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')